---
apiVersion: v1
kind: Service
metadata:
  name: sonarqube
  namespace: {{ namespace }}
  labels: {'k8s-app': 'sonarqube', 'version': 'v1'}
spec:
  selector: {'k8s-app': 'sonarqube'}
  type: NodePort
  ports:
    - protocol: TCP
      name: sonarqube
      targetPort: 9000
      port: 9000
