---
apiVersion: v1
kind: ReplicationController
metadata:
  name: sonarqube
  namespace: {{namespace}}
  labels: {'k8s-app': 'sonarqube', 'version': 'v1'}
spec:
  replicas: 1
  selector: {'k8s-app': 'sonarqube'}
  template:
    metadata:
      labels: {'k8s-app': 'sonarqube', 'version': 'v1'}
    spec:
      containers:
      - name: sonarqube
        image: {{ image }}
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
        volumeMounts:
          - mountPath: /opt/sonarqube/data
            name: sonarqube-data
          - mountPath: /opt/sonarqube/extensions
            name: sonarqube-extensions
        ports:
          - protocol: TCP
            containerPort: 9000
            name: jenkins
        env:
        - name: SONARQUBE_JDBC_USERNAME
          value: {{ db_user }}
        - name: SONARQUBE_JDBC_PASSWORD
          value: {{ db_pass }}
        - name: SONARQUBE_JDBC_URL
          value: jdbc:mysql://{{ db_host }}:3306/{{ db_name }}?useUnicode=true&characterEncoding=utf8
      volumes: {{ volumes }}
