---
apiVersion: v1
kind: ReplicationController
metadata:
  name: jenkins
  namespace: {{namespace}}
  labels: {'k8s-app': 'jenkins', 'version': 'v1'}
spec:
  replicas: 1
  selector: {'k8s-app': 'jenkins'}
  template:
    metadata:
      labels: {'k8s-app': 'jenkins', 'version': 'v1'}
    spec:
      containers:
      - name: jenkins
        image: {{ image }}
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
        volumeMounts:
          - mountPath: /var/jenkins_home
            name: jenkins-home
        ports: 
          - protocol: TCP
            containerPort: 8080
            name: jenkins
      volumes: {{ volumes }}
