---
apiVersion: "v1"
kind: "Service"
metadata:
  name: jenkins
  namespace: {{ namespace }}
  labels: {'k8s-app': 'jenkins', 'version': 'v1'}
spec:
  selector: {'k8s-app': 'jenkins'}
  type: NodePort
  ports:
    - protocol: TCP
      name: jenkins
      targetPort: 8080
      port: 8080
