---
package:
  name: jcsirot/traefik
  author: Jean-Christophe Sirot
  version: 1.0.0-rc1-1
  description: traefik
  license: MIT

variables:
  namespace: traefik
  image: containous/traefik:v1.0.0-rc1
  loglevel: DEBUG
  port:
    http: 80

resources:

  - file: traefik-configmap.yaml
    name: traefik
    type: configmap

  - file: traefik-deployment.yaml
    name: traefik
    type: deployment

  - file: traefik-daemonset.yaml
    name: traefik-proxy
    type: daemonset

  - file: traefik-svc.yaml
    name: traefik
    type: svc

  - file: traefik-dashboard-svc.yaml
    name: traefik-dashboard
    type: svc

shards: []

deploy:
  - name: $self
