---
package:
  name: jcsirot/traefik
  author: Jean-Christophe Sirot
  version: 1.0.0-beta
  description: traefik
  license: MIT

variables:
  namespace: traefik
  image: containous/traefik
  loglevel: DEBUG

resources:
  - file: traefik-daemonset.yaml
    name: traefik
    type: daemonset

  - file: traefik-dashboard-svc.yaml
    name: traefik-dashboard
    type: svc

  - file: traefik-configmap.yaml
    name: traefik
    type: configmap

shards: []

deploy:
  - name: $self
