---
apiVersion: v1
kind: Service
metadata:
  name: supervisor
spec:
  ports:
  - name: worker-1
    port: 6700
    targetPort: 6700
    protocol: TCP
  - name: worker-2
    port: 6701
    targetPort: 6701
    protocol: TCP
  - name: worker-3
    port: 6702
    targetPort: 6702
    protocol: TCP
  - name: worker-4
    port: 6703
    targetPort: 6703
    protocol: TCP
  selector:
    app: apache-storm-supervisor
