---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nimbus
data:
  storm.yaml: |-
    nimbus.seeds :
      - nimbus.default.svc.cluster.local
    storm.zookeeper.servers:
    {% for zk in zookeeper.hosts %}
      - {{ zk }}
    {% endfor %}
    storm.zookeeper.port: {{zookeeper.port}}
    storm.local.dir: "/mnt/storm"

  env.ini: |-
    [environment]
