---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
spec:
  ports:
  - name: client
    port: 2181
    protocol: TCP
    targetPort: 2181
    nodePort: 30000
  - name: peer
    port: 2888
    protocol: TCP
    targetPort: 2888
  - name: leader
    port: 3888
    protocol: TCP
    targetPort: 3888
  type: NodePort
  selector:
    app: zookeeper
